"""Instructor-run weekly newsletter built from read-only student repository evidence."""

from .collect import EvidenceLimits, WeeklyEvidenceCollector, project_label
from .compose import (
    EDITORIAL_MARKER,
    EDITORIAL_SCHEMA,
    HIGHLIGHTS_MARKER,
    HIGHLIGHTS_SCHEMA,
    EditorialDraft,
    LinkChecker,
    NewsletterCompositionError,
    NewsletterWriter,
    OpenAINewsletterWriter,
    build_editorial_system_prompt,
    build_editorial_user_prompt,
    build_highlights_system_prompt,
    build_highlights_user_prompt,
    compose_editorial,
    compose_highlights,
    compose_newsletter,
    describe_project,
    link_resolves,
    quote_candidates,
    validate_editorial,
    validate_highlights,
)
from .images import (
    FoundImage,
    HighlightImageFinder,
    ImageCandidate,
    ImageJudge,
    PlaywrightImageFinder,
    build_judge_prompt,
    discover_week_anchor,
    discover_week_pages,
    filter_candidates,
)
from .lecture import (
    LectureNotes,
    compact_slides_text,
    learning_goals_from_syllabus,
    load_lecture_notes,
)
from .models import (
    CommitSummary,
    CourseWeek,
    Delivery,
    Highlight,
    HighlightImage,
    NewsletterBranding,
    NewsletterCopy,
    NewsletterIssue,
    NewsletterSettings,
    PioneerQuote,
    ProjectDocument,
    ProjectEvidence,
    ProjectLink,
    ProjectScore,
    WeeklyDigest,
    issue_id_for,
)
from .quotes import PIONEER_QUOTES, choose_quote
from .render import cid_image_source, relative_image_source, render_html, render_text
from .schedule import NewsletterScheduleError, load_schedule, parse_schedule, select_week
from .score import (
    MIN_GOAL_FIT,
    SCORE_SCHEMA,
    SCORE_WEIGHTS,
    SCORING_MARKER,
    NewsletterScoringError,
    parse_score,
    score_projects,
    select_highlights,
    verify_quote,
)
from .screenshots import ScreenshotError, SiteScreenshot, encode_jpeg
from .service import NewsletterService, NewsletterStateError, normalize_recipients
from .store import FileNewsletterStore, NewsletterStoreError

__all__ = [
    "EDITORIAL_MARKER",
    "EDITORIAL_SCHEMA",
    "HIGHLIGHTS_MARKER",
    "HIGHLIGHTS_SCHEMA",
    "MIN_GOAL_FIT",
    "PIONEER_QUOTES",
    "SCORE_SCHEMA",
    "SCORE_WEIGHTS",
    "SCORING_MARKER",
    "CommitSummary",
    "CourseWeek",
    "Delivery",
    "EditorialDraft",
    "EvidenceLimits",
    "FileNewsletterStore",
    "FoundImage",
    "Highlight",
    "HighlightImage",
    "HighlightImageFinder",
    "ImageCandidate",
    "ImageJudge",
    "LectureNotes",
    "LinkChecker",
    "NewsletterBranding",
    "NewsletterCompositionError",
    "NewsletterCopy",
    "NewsletterIssue",
    "NewsletterScheduleError",
    "NewsletterScoringError",
    "NewsletterService",
    "NewsletterSettings",
    "NewsletterStateError",
    "NewsletterStoreError",
    "NewsletterWriter",
    "OpenAINewsletterWriter",
    "PioneerQuote",
    "PlaywrightImageFinder",
    "ProjectDocument",
    "ProjectEvidence",
    "ProjectLink",
    "ProjectScore",
    "ScreenshotError",
    "SiteScreenshot",
    "WeeklyDigest",
    "WeeklyEvidenceCollector",
    "build_editorial_system_prompt",
    "build_editorial_user_prompt",
    "build_highlights_system_prompt",
    "build_highlights_user_prompt",
    "build_judge_prompt",
    "choose_quote",
    "cid_image_source",
    "compact_slides_text",
    "compose_editorial",
    "compose_highlights",
    "compose_newsletter",
    "describe_project",
    "discover_week_anchor",
    "discover_week_pages",
    "encode_jpeg",
    "filter_candidates",
    "issue_id_for",
    "learning_goals_from_syllabus",
    "link_resolves",
    "load_lecture_notes",
    "load_schedule",
    "normalize_recipients",
    "parse_schedule",
    "parse_score",
    "project_label",
    "quote_candidates",
    "relative_image_source",
    "render_html",
    "render_text",
    "score_projects",
    "select_highlights",
    "select_week",
    "validate_editorial",
    "validate_highlights",
    "verify_quote",
]
