"""Instructor-run weekly newsletter built from read-only student repository evidence."""

from .collect import EvidenceLimits, WeeklyEvidenceCollector, project_label
from .compose import (
    NEWSLETTER_COPY_SCHEMA,
    NewsletterCompositionError,
    NewsletterWriter,
    OpenAINewsletterWriter,
    build_system_prompt,
    build_user_prompt,
    compose_newsletter,
    describe_project,
    validate_copy,
)
from .images import (
    FoundImage,
    HighlightImageFinder,
    ImageCandidate,
    ImageJudge,
    PlaywrightImageFinder,
    build_judge_prompt,
    discover_week_anchor,
    discover_week_pages,
    filter_candidates,
)
from .models import (
    CommitSummary,
    CourseWeek,
    Delivery,
    Highlight,
    HighlightImage,
    NewsletterBranding,
    NewsletterCopy,
    NewsletterIssue,
    NewsletterSettings,
    PioneerQuote,
    ProjectDocument,
    ProjectEvidence,
    ProjectLink,
    ProjectScore,
    WeeklyDigest,
    issue_id_for,
)
from .quotes import PIONEER_QUOTES, choose_quote
from .render import cid_image_source, relative_image_source, render_html, render_text
from .schedule import NewsletterScheduleError, load_schedule, parse_schedule, select_week
from .score import (
    MIN_GOAL_FIT,
    SCORE_SCHEMA,
    SCORE_WEIGHTS,
    SCORING_MARKER,
    NewsletterScoringError,
    parse_score,
    score_projects,
    select_highlights,
)
from .screenshots import ScreenshotError, SiteScreenshot, encode_jpeg
from .service import NewsletterService, NewsletterStateError, normalize_recipients
from .store import FileNewsletterStore, NewsletterStoreError

__all__ = [
    "MIN_GOAL_FIT",
    "NEWSLETTER_COPY_SCHEMA",
    "PIONEER_QUOTES",
    "SCORE_SCHEMA",
    "SCORE_WEIGHTS",
    "SCORING_MARKER",
    "CommitSummary",
    "CourseWeek",
    "Delivery",
    "EvidenceLimits",
    "FileNewsletterStore",
    "FoundImage",
    "Highlight",
    "HighlightImage",
    "HighlightImageFinder",
    "ImageCandidate",
    "ImageJudge",
    "NewsletterBranding",
    "NewsletterCompositionError",
    "NewsletterCopy",
    "NewsletterIssue",
    "NewsletterScheduleError",
    "NewsletterScoringError",
    "NewsletterService",
    "NewsletterSettings",
    "NewsletterStateError",
    "NewsletterStoreError",
    "NewsletterWriter",
    "OpenAINewsletterWriter",
    "PioneerQuote",
    "PlaywrightImageFinder",
    "ProjectDocument",
    "ProjectEvidence",
    "ProjectLink",
    "ProjectScore",
    "ScreenshotError",
    "SiteScreenshot",
    "WeeklyDigest",
    "WeeklyEvidenceCollector",
    "build_judge_prompt",
    "build_system_prompt",
    "build_user_prompt",
    "choose_quote",
    "cid_image_source",
    "compose_newsletter",
    "describe_project",
    "discover_week_anchor",
    "discover_week_pages",
    "encode_jpeg",
    "filter_candidates",
    "issue_id_for",
    "load_schedule",
    "normalize_recipients",
    "parse_schedule",
    "parse_score",
    "project_label",
    "relative_image_source",
    "render_html",
    "render_text",
    "score_projects",
    "select_highlights",
    "select_week",
    "validate_copy",
]
