"""Instructor-run weekly newsletter built from read-only student repository evidence."""

from .collect import EvidenceLimits, WeeklyEvidenceCollector, project_label
from .compose import (
    NEWSLETTER_COPY_SCHEMA,
    NewsletterCompositionError,
    NewsletterWriter,
    OpenAINewsletterWriter,
    build_system_prompt,
    build_user_prompt,
    compose_newsletter,
    validate_copy,
)
from .models import (
    CommitSummary,
    CourseWeek,
    Delivery,
    Highlight,
    HighlightImage,
    NewsletterBranding,
    NewsletterCopy,
    NewsletterIssue,
    NewsletterSettings,
    PioneerQuote,
    ProjectDocument,
    ProjectEvidence,
    ProjectLink,
    WeeklyDigest,
    issue_id_for,
)
from .quotes import PIONEER_QUOTES, choose_quote
from .render import cid_image_source, relative_image_source, render_html, render_text
from .schedule import NewsletterScheduleError, load_schedule, parse_schedule, select_week
from .screenshots import (
    PlaywrightScreenshotter,
    ScreenshotError,
    SiteScreenshot,
    SiteScreenshotter,
    encode_jpeg,
)
from .service import NewsletterService, NewsletterStateError, normalize_recipients
from .store import FileNewsletterStore, NewsletterStoreError

__all__ = [
    "NEWSLETTER_COPY_SCHEMA",
    "PIONEER_QUOTES",
    "CommitSummary",
    "CourseWeek",
    "Delivery",
    "EvidenceLimits",
    "FileNewsletterStore",
    "Highlight",
    "HighlightImage",
    "NewsletterBranding",
    "NewsletterCompositionError",
    "NewsletterCopy",
    "NewsletterIssue",
    "NewsletterScheduleError",
    "NewsletterService",
    "NewsletterSettings",
    "NewsletterStateError",
    "NewsletterStoreError",
    "NewsletterWriter",
    "OpenAINewsletterWriter",
    "PioneerQuote",
    "PlaywrightScreenshotter",
    "ProjectDocument",
    "ProjectEvidence",
    "ProjectLink",
    "ScreenshotError",
    "SiteScreenshot",
    "SiteScreenshotter",
    "WeeklyDigest",
    "WeeklyEvidenceCollector",
    "build_system_prompt",
    "build_user_prompt",
    "choose_quote",
    "cid_image_source",
    "compose_newsletter",
    "encode_jpeg",
    "issue_id_for",
    "load_schedule",
    "normalize_recipients",
    "parse_schedule",
    "project_label",
    "relative_image_source",
    "render_html",
    "render_text",
    "select_week",
    "validate_copy",
]
